import { useState, type FormEvent } from 'react'
import { Check, ChevronDown, MailPlus, MoreHorizontal, Shield, Users } from 'lucide-react'
import { api } from '../services/api'
import type { AccessLevel, Area, Member } from '../types'

export function AdminPanel({ members, areas, onMemberSaved }: { members: Member[]; areas: Area[]; onMemberSaved: (member: Member) => void }) {
  const [selectedId, setSelectedId] = useState(members[0]?.id)
  const selected = members.find((member) => member.id === selectedId)
  const [saved, setSaved] = useState(false)
  const [inviteOpen, setInviteOpen] = useState(false)

  async function updateMembership(area: string, access: AccessLevel | 'none') {
    if (!selected) return
    const memberships = { ...selected.memberships }
    if (access === 'none') delete memberships[area]; else memberships[area] = access
    const updated = await api.saveMember({ ...selected, memberships })
    onMemberSaved(updated); setSaved(true); window.setTimeout(() => setSaved(false), 1600)
  }

  return <div className="admin-panel flex min-h-0 flex-1 flex-col overflow-auto bg-[#141611]">
    <header className="admin-header flex min-h-[62px] items-center gap-3 border-b border-line px-6"><div className="grid h-9 w-9 place-items-center rounded-lg bg-sky-400/10 text-sky-300"><Users size={18} /></div><div className="min-w-0 flex-1"><p className="text-[10px] uppercase tracking-[.15em] text-muted">Administración</p><h2 className="truncate font-medium">Personas y accesos</h2></div><button className="primary-button" aria-label="Invitar persona" onClick={() => setInviteOpen(true)}><MailPlus size={15} /> <span>Invitar persona</span></button></header>
    <div className="admin-grid mx-auto grid w-full max-w-6xl gap-6 p-6 lg:grid-cols-[1fr_1.15fr]">
      <section className="surface-card overflow-hidden"><div className="flex items-center justify-between border-b border-line p-4"><div><h3 className="text-sm font-medium">Miembros</h3><p className="mt-1 text-xs text-muted">{members.length} personas en la organización</p></div><button className="icon-button"><MoreHorizontal size={16} /></button></div><div className="divide-y divide-line">{members.map((member) => <button key={member.id} onClick={() => setSelectedId(member.id)} className={`member-row ${selectedId === member.id ? 'active' : ''}`}><span className="avatar">{member.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</span><span className="min-w-0 flex-1 text-left"><strong className="block truncate text-sm font-medium">{member.name}</strong><span className="block truncate text-xs text-muted">{member.email}</span></span><span className={`status-dot ${member.status}`} />{member.role === 'admin' && <Shield size={14} className="text-moss" />}</button>)}</div></section>
      <section className="surface-card overflow-hidden">{selected ? <><div className="border-b border-line p-5"><div className="member-detail-head flex items-start gap-4"><span className="avatar large">{selected.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</span><div className="min-w-0 flex-1"><h3 className="font-medium">{selected.name}</h3><p className="mt-1 truncate text-xs text-muted">{selected.email}</p></div><span className="rounded-full border border-line px-2.5 py-1 text-[10px] uppercase tracking-wider text-muted">{selected.role === 'admin' ? 'Administrador' : 'Miembro'}</span></div></div><div className="p-5"><div className="mb-4 flex items-center justify-between"><div><h4 className="text-sm font-medium">Acceso por área</h4><p className="mt-1 text-xs text-muted">Los cambios se guardan automáticamente.</p></div>{saved && <span className="flex items-center gap-1 text-xs text-moss"><Check size={13} /> Guardado</span>}</div><div className="space-y-2">{areas.map((area) => <div key={area.key} className="admin-area-row flex items-center gap-3 rounded-lg border border-line bg-ink/40 p-3"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: area.color }} /><div className="min-w-0 flex-1"><strong className="block text-sm font-medium">{area.name}</strong><span className="text-xs text-muted">{area.description}</span></div><span className="relative"><select value={selected.memberships[area.key] ?? 'none'} onChange={(event) => void updateMembership(area.key, event.target.value as AccessLevel | 'none')} className="admin-access-select appearance-none rounded-md border-line bg-panel py-1.5 pl-3 pr-8 text-xs text-stone-200 focus:border-moss/40 focus:ring-moss/20"><option value="none">Sin acceso</option><option value="read">Lectura</option><option value="write">Escritura</option><option value="manage">Administración</option></select><ChevronDown size={12} className="pointer-events-none absolute right-2.5 top-1/2 -translate-y-1/2 text-muted" /></span></div>)}</div></div></> : null}</section>
    </div>{inviteOpen && <InviteDialog areas={areas} onClose={() => setInviteOpen(false)} onInvite={async (member) => { const savedMember = await api.saveMember(member); onMemberSaved(savedMember); setSelectedId(savedMember.id); setInviteOpen(false) }} />}
  </div>
}

function InviteDialog({ areas, onClose, onInvite }: { areas: Area[]; onClose: () => void; onInvite: (member: Member) => Promise<void> }) {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [area, setArea] = useState(areas[0]?.key ?? ''); const [access, setAccess] = useState<AccessLevel>('read')
  function submit(event: FormEvent) { event.preventDefault(); if (!name.trim() || !email.includes('@')) return; void onInvite({ id: crypto.randomUUID(), name: name.trim(), email: email.trim().toLowerCase(), role: 'member', status: 'invited', memberships: area ? { [area]: access } : {} }) }
  return <div className="modal-backdrop"><form className="modal-card invite-modal max-w-md p-6" onSubmit={submit}><p className="eyebrow">Nueva invitación</p><h2 className="mt-1 text-xl font-medium">Invitar a la organización</h2><div className="mt-6 space-y-4"><label className="block"><span className="field-label">Nombre</span><input className="field" autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Nombre de la persona" /></label><label className="block"><span className="field-label">Correo</span><input className="field" type="email" inputMode="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="persona@empresa.com" /></label><div className="invite-fields grid grid-cols-2 gap-3"><label><span className="field-label">Área inicial</span><select className="field" value={area} onChange={(event) => setArea(event.target.value)}>{areas.map((item) => <option key={item.key} value={item.key}>{item.name}</option>)}</select></label><label><span className="field-label">Acceso</span><select className="field" value={access} onChange={(event) => setAccess(event.target.value as AccessLevel)}><option value="read">Lectura</option><option value="write">Escritura</option><option value="manage">Administración</option></select></label></div></div><div className="modal-actions mt-6 flex justify-end gap-3"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={!name.trim() || !email.includes('@')}>Crear invitación</button></div></form></div>
}
